# Numpy 

In [2]:
import numpy as np

In [4]:
list1=[1,2,3,4,5]
arr=np.array(list1)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(5,)

In [8]:
list2=[3,4,5,6,7]
list3=[6,7,8,9,1]
arr1=np.array([list1,list2,list3])
arr1

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [6, 7, 8, 9, 1]])

In [9]:
arr1.shape

(3, 5)

In [10]:
arr1.reshape(5,3)
arr1

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [6, 7, 8, 9, 1]])

In [11]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 3],
       [4, 5, 6],
       [7, 6, 7],
       [8, 9, 1]])

In [12]:
arr1

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [6, 7, 8, 9, 1]])

In [13]:
arr2=arr1.reshape(5,3)
arr2

array([[1, 2, 3],
       [4, 5, 3],
       [4, 5, 6],
       [7, 6, 7],
       [8, 9, 1]])

In [14]:
arr[1]

2

In [15]:
arr1[1,1]

4

In [16]:
arr1[0,1]

2

In [17]:
arr1[1,1:3]

array([4, 5])

In [18]:
arr1[0,1:3]

array([2, 3])

In [19]:
arr1

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [6, 7, 8, 9, 1]])

In [20]:
arr1[1:,3:]

array([[6, 7],
       [9, 1]])

In [23]:
arr1[0:2,2:4]

array([[3, 4],
       [5, 6]])

In [22]:
arr1[1,1:4]

array([4, 5, 6])

In [27]:
arr1=np.arange(0,10,2)
arr1

array([0, 2, 4, 6, 8])

In [40]:
lst1=[11,22,33,44,55]
lst2=[10,9,8,7,6]
lst3=[11,12,13,14,15]
ar1=np.array([lst1,lst2,lst3])
ar1

array([[11, 22, 33, 44, 55],
       [10,  9,  8,  7,  6],
       [11, 12, 13, 14, 15]])

In [41]:
ar1=np.arange(0,10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Arange is used the write the numbers from (start,stop) start to stop irrespective of the elements in the array
- The stop number is not considered

In [42]:
ar1=np.arange(10,20,5)

In [43]:
ar1

array([10, 15])

In [44]:
ar2=np.linspace(0,10,50)
ar2

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [45]:
ar3=np.arange(20,30,0.5)
ar3

array([20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. ,
       25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5])

In [46]:
ar3=(1,2,3,4,5,6,7,8,9)
ar3

(1, 2, 3, 4, 5, 6, 7, 8, 9)

In [47]:
type(ar3)

tuple

In [48]:
ar3=[1,2,3,4,5,6,7,8,9]
type(ar3)

list

In [49]:
ar3=np.array(ar3)

In [50]:
type(ar3)

numpy.ndarray

In [51]:
ar3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Copy and Broadcasting funtion


- This is how braodcasting works i.e array is a reference type so we can say that each array share the same memory cell so change in one array value results in change of another array too
- In order to solve this problem, we use copy function where copy creates another memory location instead of using the same one which happens in broadcasting function

In [52]:
ar3[3:]=100
ar3

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [57]:
ar4=ar3
#broadcasting occurs in this condition
ar4[3:]=500
ar3
ar4

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [54]:
ar3

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [55]:
ar4

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [58]:
lst=[1,2,3,4,5,6,7,8,9]
arr3=np.array(lst)
type(arr3)

numpy.ndarray

In [59]:
arr3[3:]=100
arr3

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [61]:
arr4=np.copy(arr3)
arr4

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [62]:
arr4[3:]=500
arr4

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [63]:
arr3

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [64]:
arr5=arr4.copy()
arr5

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [65]:
print(arr3)
print(arr4)
print(arr5)

[  1   2   3 100 100 100 100 100 100]
[  1   2   3 500 500 500 500 500 500]
[  1   2   3 500 500 500 500 500 500]


### Some useful condtions in array

In [67]:
# variable declaartion
val=2
arr3<2

array([ True, False, False, False, False, False, False, False, False])

In [69]:
arr3<100

array([ True,  True,  True, False, False, False, False, False, False])

In [70]:
arr3*2

array([  2,   4,   6, 200, 200, 200, 200, 200, 200])

In [71]:
arr3

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [72]:
arr3[arr3<val]

array([1])

In [73]:
arr3[arr3<100]

array([1, 2, 3])

In [75]:
print(arr3[arr3<100])

[1 2 3]


## Arange and reshape

In [76]:
arr6=np.arange(0,10,1).reshape(10,1)
arr6

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [78]:
arr6.reshape(1,10)


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [79]:
arr7=arr6.reshape(1,10)
arr7

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [80]:
arr6

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [81]:
arr8=np.arange(0,20,2).reshape(5,2)
print(arr8)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


### np.ones() is  used to print numbers of ones

In [88]:
arr1=np.ones(1)
arr1

array([1.])

In [84]:
arr2=np.ones((2,2))
arr2

array([[1., 1.],
       [1., 1.]])

In [85]:
arr3=np.ones((2,2),dtype=int)
arr3

array([[1, 1],
       [1, 1]])

In [86]:
arr4=np.ones((3,3),dtype=float)
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Random is used to print random values from 0 to 1

In [92]:
arr1=np.random.rand(2,2)
arr1

array([[0.6259223 , 0.68354432],
       [0.97970329, 0.42774985]])

### randn is used to select random standard normal distribution

In [95]:
arr2=np.random.randn(5,5)
arr2

array([[ 1.20397557, -1.52320034, -0.6666574 , -0.76079106, -0.19906857],
       [ 1.82581162,  0.20577946,  0.55288198,  1.38426626, -1.51918622],
       [ 1.0304362 , -0.01772251,  0.22530584, -0.73621267, -0.58479726],
       [ 0.91053129, -1.79663125,  0.81909016,  0.15592119,  0.18922383],
       [-1.21109746, -0.21564484, -0.41021814,  0.44678638,  0.82089592]])

### randint is used to generate  ranom integer values between the specified range

In [97]:
arr1=np.random.randint(1,10,5)
arr1

array([4, 8, 4, 3, 2])

In [99]:
arr2=np.random.randint(1,100,20).reshape(5,4)
arr2

array([[48, 11, 36, 82],
       [72, 69, 73, 23],
       [64, 23, 55, 10],
       [13, 97, 26, 33],
       [32, 84, 74, 66]])

### random_sample return random floats in the half-open interval [0.0, 1.0) where the numbers inside the bracket    ( a,b) is the size of the array

In [102]:
arr1=np.random.random_sample((5,5))
arr1

array([[0.6978252 , 0.30694573, 0.46514109, 0.90657434, 0.05060981],
       [0.58956411, 0.52871259, 0.1837709 , 0.41791775, 0.36525452],
       [0.82142885, 0.45203257, 0.02910314, 0.73403748, 0.94121334],
       [0.56292782, 0.65650777, 0.67206146, 0.37062112, 0.79381791],
       [0.26019661, 0.90774232, 0.89196272, 0.40608671, 0.71104205]])